'use strict';(function(h){var d=window.AmazonUIPageJS||window.P,l=d._namespace||d.attributeErrors,k=l?l("AudibleWebSearchAssets",""):d;k.guardFatal?k.guardFatal(h)(k,window):k.execute(function(){h(k,window)})})(function(h,d,l){var k=function(){function f(a,e){for(var c=0;c<e.length;c++){var b=e[c];b.enumerable=b.enumerable||!1;b.configurable=!0;"value"in b&&(b.writable=!0);Object.defineProperty(a,b.key,b)}}return function(a,e,c){e&&f(a.prototype,e);c&&f(a,c);return a}}();h.register("InMemorySearch",
function(){return function(){function f(a){var e=this;if(!(this instanceof f))throw new TypeError("Cannot call a class as a function");var c={};Object.keys(a).forEach(function(b){return c[e._cleanQuery(b)]=a[b]});this._data=c;this._cachedResultsByQuery={}}k(f,[{key:"search",value:function(a){var e=this;a=this._cleanQuery(a);var c=this._cachedResultsByQuery[a];if(c)return c;c=this._cachedResultsByQuery[a]=[];Object.keys(this._data).forEach(function(b){-1<b.indexOf(a)&&c.push(e._prepareResult(b))});
return c}},{key:"exactSearch",value:function(a){a=this._cleanQuery(a);return this._prepareResult(a)}},{key:"_cleanQuery",value:function(a){return String(a).toLowerCase().trim()}},{key:"_prepareResult",value:function(a){var e=this._data[a];e&&e.key===l&&(e.key=a);return e||null}}]);return f}()});"use strict";h.when("autocomplete","searchAjax").register("searchUiInit",function(f,a){var e=function(c,b){return a.fetchSuggestions(c.display,b)};return function(c){var a=c.querySelectorAll(".search-autocomplete");
c=function(c){c=a[c];var b=f(c,e),d=c.getElementsByClassName("search-advanced-suggestion-link")[0];if(d)b.on("repositionSuggestions",function(c,a){a.showBelow?a.suggestionsWrapper.appendChild(d):a.suggestionsWrapper.insertBefore(d,a.suggestionsWrapper.childNodes[0])})};for(var d=0;d<a.length;d++)c(d)}});h.when("searchUiInit","ready").register("searchUi",function(d){d(document);return{}});"use strict";h.when("fetch","ready").register("searchAjax",function(){var f=/iPhone|iPad|iPod|Android|Blackberry|Opera Mini|IEMobile/i.test(navigator.userAgent)?
"mobile":"desktop",a=document.getElementById("adbl-nav-search-ref-override")?""+document.getElementById("adbl-nav-search-ref-override").value:"",e=function(a,b,d,e,f){return document.location.protocol+"//"+a+"/1.0/searchsuggestions?"+("\x26key_strokes\x3d"+encodeURIComponent(b))+("\x26site_variant\x3d"+d)+("\x26session_id\x3d"+e)+("\x26local_time\x3d"+encodeURIComponent(f))};return{fetchSuggestions:function(c,b){c=String(c).toLowerCase().trim();var h=d.autocomplete_config||{},k=0===c.length,l=new Date,
q=e(h.apiEndpoint,c,f,d.digitalData?d.digitalData.webSessionId:"",(new Date(l.getTime()-6E4*l.getTimezoneOffset())).toISOString().slice(0,19));d.fetch(q,{method:"GET",mode:"cors",credentials:"include",headers:{"Client-ID":"AudibleWebSearch","Accept-Language":h.acceptLanguage}}).catch(function(a){b(null);throw Error("Autocomplete: searchAjax call failed");}).then(function(a){if(204!==a.status)return a.json()}).then(function(d){d&&function(){var e=(new Date).getTime()-l.getTime(),f=d.model,h=f.items,
n=f.api_data;f=f.section_header;var m=n.logging_data,q=n.eac_query_string,p=[],r=1,t=1,u=1,v=1;e={suggestionMetaData:{crid:n.cr_id,sprefix:[c,m.search_index,e].join(),i:m.search_index,url:"search-alias\x3d"+m.search_index},eactsMetadata:{qid:m.query_id,alias_or_index:m.search_index,total_found:n.total_found,rank:m.rank_order,sr_prefix:m.sr_prefix},suggestions:h.filter(function(a){return"AISearchPrompts"!==a.view.template}).map(function(c,e){var d=c.view,b=c.model,g=("AuthorItemV2"===d.template?b.action.payload:
b.tap_action.payload).metadata,f=null;e+=1;"ListItem"===d.template?(d=g.isISS,b=g.keywords,f=k?null:a,g=k?"web_search_suggested_keyword_"+(e+"_"+g.model_rank+"_")+a:d?g.refmarker:"web_search_eac_keyword_"+t,t++):"AuthorItemV2"===d.template?(b=b.person_metadata.asin,b||(b=g.asin),p.push(b),b=g.keywords,g=k?"web_search_suggested_ath_"+(e+"_"+(g.model_rank?g.model_rank:1)):"web_search_eac_ath_"+u,u++):"CollectionRowItem"===d.template?(d=b.series_asin,d||(d=g.asin),p.push(d),b=b.keywords,g=k?"web_search_suggested_srs_"+
(e+"_"+(g.model_rank?g.model_rank:1)):"web_search_eac_srs_"+v,v++):(b=b.product_metadata.asin,b||(b=g.asin),p.push(b),b=g.keywords,g=k?"web_search_suggested_asin_"+(e+"_"+g.model_rank):"web_search_eac_asin_"+r,r++);return{index:e,item:c,ref:g,ref_override:f,display:b}}),aiPrompts:h.filter(function(a){return"AISearchPrompts"===a.view.template}).map(function(a){return{header:a.model.header,prompts:a.model.prompts||a.model.items,asosId:a.model.asosId}})[0]||null,eacImpressions:p,eacQueryString:q,trendingSearchHeader:f};
b(e)}()})}}})});