'use strict';(function(g){var f=window.AmazonUIPageJS||window.P,p=f._namespace||f.attributeErrors,a=p?p("AudibleWebSpecialPromoAssets",""):f;a.guardFatal?a.guardFatal(g)(a,window):a.execute(function(){g(a,window)})})(function(g,f,p){g.when("AudiblejQuery","countdownTimer","refMarkers").execute(function(a,A,k){function h(m){g.register("specialPromo",function(){var h=function(){var h=0<a("#isInSpecialPromoCart").length,r=0<f.navigator.userAgent.indexOf("MSIE ")||navigator.userAgent.match(/Trident.*rv:11\./)?
"POST":"GET",w=a("#showSpecialPromoTray").data("marketplaceId"),t=!1;f.location.search&&-1!=f.location.search.indexOf("isRedirectedFromWasabiAuth\x3dtrue")&&(t=!0);var x=String(f.location.search).match(/(referrerPlatform=[^&]+)/g);a(".addToSpecialPromoTrayBtn").click(function(){var b=a(this);g.now("specialPromoBuyBoxCallBacks").execute(function(a){"undefined"!==typeof a?l(b,null,a.addToSpecialPromoTrayCallBack):l(b,null,null);k.buildAndPost("add",this)})});var y=function(a){a=a.next(".spActionData");
var b=a.data("url");return b?b:a.data()},n=function(b){function c(){a("#sp-floating-cart .togglable").toggle();e.toggleClass("bc-pub-hidden")}var e=a("#cart-normal"),d=a("#sp-floating-cart");d.css("transition-duration",b?"0s":"0.4s");if(e.is(":visible")){if(b)c();else d.on("webkitTransitionEnd transitionend otransitionEnd mozTransitionEnd",function(){c();d.off("webkitTransitionEnd transitionend otransitionEnd mozTransitionEnd")});b=m?"68px":"108px";m?(d.css("height",b),a("#sp-floating-cart").css("padding-top",
"0px")):d.css("max-height",b)}else c(),m?d.css("height","calc(100% - 56px)"):d.css("max-height","600px")},u=function(){k.buildAndPost("proceedCheckout",void 0);a(".removeFromSpecialPromoTrayBtn").toggle();a("#cart-confirm-checkout-btn").toggle();a("#sp-cart-edit-order").toggleClass("bc-pub-hidden");a("#cart-checkout-btn").toggleClass("bc-pub-hidden");a("#cart-payment-method-link").toggleClass("bc-pub-hidden");a("#back-to-sale").toggle()},C=function(){a(".fold-btns").click(function(){a(".cart-item-small.added img").removeClass("zoom-in");
n();k.buildAndPost("toggleCart",this);a("#sp-floating-cart").on("webkitTransitionEnd transitionend otransitionEnd mozTransitionEnd",function(){a(".fold-btns").focus();a("#sp-floating-cart").off("webkitTransitionEnd transitionend otransitionEnd mozTransitionEnd")})});a("#cart-confirm-checkout-btn").click(function(){var b=a(this);u();v(b,!1)});a("#sp-cart-edit-order button").click(function(){u()});a("#cart-checkout-btn button").click(function(){k.buildAndPost("confirmPurchase",this);B(a(this).parent())});
a(".removeFromSpecialPromoTrayBtn").click(function(){var b=a(this);g.now("specialPromoBuyBoxCallBacks").execute(function(a){a!==p?l(b,null,a.removeFromSpecialPromoTrayCallBack):l(b,null,null);k.buildAndPost("remove",b)})});a("#creditButton, #cashButton").click(function(){a(".sp-pdp-buybox-wrap").hide();a("#sp-buybox-more-options-dropdown").hide()});a(".sp-more-options-expander-area").click(function(){k.buildAndPost("moreOptions",this)});if(t){u();n();t=!1;var b=f.location.search;b&&f.history&&f.history.pushState&&
(b=b.replace("isRedirectedFromWasabiAuth\x3dtrue","isRedirectedFromWasabiAuth\x3dfalse"),f.history.pushState(null,null,b))}},z=function(b,c,e){var d="/special-promo/cart.htm";x&&(d=d+"?"+x);a.ajax({url:d,type:r,data:{asin:null,isInCart:h,marketplaceId:w,spCartPageUri:f.location.pathname,spCartPageParams:f.location.search},cache:!1}).done(function(d){0<a("#sp-floating-cart").length?a("#sp-floating-cart").replaceWith(d):a("body").append(d);C();"remove"===b&&(a("#empty-cart-indicator").length||n(!0));
"add"===b&&(a(".cart-item-small.added:last img").addClass("zoom-in"),!a("#cart-normal").is(":visible")&&a("#full-cart-indicator").length&&n(!0));A.start();a("body").css("margin-bottom",m?"70px":"110px");a.isFunction(c)&&c(e)})},l=function(b,c,e){c||(c=y(b));c&&a.ajax({url:c,type:r,dataType:"json",data:{marketplaceId:w},cache:!1}).done(function(a){a.succeed?z(a.updateAction,e,b):(console.error("update cart failed, errMeg:",a.errorMessage),q(null,a.errorMessage))})},v=function(b,c){var e="cart-checkout-btn"===
b.attr("id")?!0:!1,d=b.find("button.bc-button-text");!0===c?(b.addClass("bc-button-disabled"),d.prop("disabled",!0),e&&(a("#sp-cart-edit-order").hide(),d.text(a("#sp-checkout-btn-processing").data("processing")))):(b.removeClass("bc-button-disabled"),d.prop("disabled",!1),e&&(a("#sp-cart-edit-order").show(),d.text(a("#sp-checkout-btn-confirm-purchase").data("confirm"))))},B=function(b){v(b,!0);var c=y(b);c={url:c.extraCreditsCheckoutUrl||c.bookCheckoutUrl,type:r,dataType:"json",data:{src:encodeURI(f.location.pathname+
f.location.search)},cache:!1};a.ajax(c).done(D).fail(E).always(function(){v(b,!1)})},D=function(a){!0===a.isSuccessful?f.location.href=a.redirectUrl:q(a.spError)},E=function(a){if(401==a.status&&a.responseText)try{var b=JSON.parse(a.responseText);b&&b.redirectToLoginPath&&f.location.replace(b.redirectToLoginPath)}catch(e){q(5)}else q(5)},q=function(b,c){var e=a("#sp-tray-error");if(e.length){e.find(".error").addClass("bc-pub-hidden");m?a("#sp-floating-cart").css("height","calc(100% - 56px)"):a("#sp-floating-cart").css("max-height",
"600px");var d=a("#cart-normal");d.is(":visible")||(a("#sp-floating-cart .togglable").toggle(),d.toggleClass("bc-pub-hidden"));c?e.removeClass("bc-pub-hidden").find(".error-custom").removeClass("bc-pub-hidden").text(c):(b&&0!==e.find(".error-"+b).length||(b=5),e.removeClass("bc-pub-hidden").find(".error-"+b).removeClass("bc-pub-hidden"))}};return{addToCart:function(a,c,e){return l(a,c,e)},removeFromCart:function(a,c,e){return l(a,c,e)},loadCart:function(a,c){return z(a,c)},toggleCartFold:function(){return n()}}}();
h.loadCart();return{cartHelper:h}})}a("#showSpecialPromoTray").length&&(g.when("mobile").execute(function(){h(!0)}),g.when("desktop").execute(function(){h(!1)}))})});