'use strict';(function(g){var f=window.AmazonUIPageJS||window.P,h=f._namespace||f.attributeErrors,a=h?h("AudibleProductContentAssets",""):f;a.guardFatal?a.guardFatal(g)(a,window):a.execute(function(){g(a,window)})})(function(g,f,h){g.when("initPlayerButton","initAllPlayers","ready").execute(function(a){function e(){var c;return function(b,u){if(b!==c&&c!==h){var d=document.getElementById("sample-player-"+c);a.template(d,k.UNAVAILABLE)}d=document.getElementById("sample-player-"+b);a.template(d,k[u]);
c=b}}function b(a){a=a.getAttribute("data-trigger");if(!a)return null;a=a.split("-");return 3>a.length?null:a[2]}function d(a,c){return function(d){d.preventDefault();if(d=b(a))return c.onPlaySampleClicked(d),!1}}function c(a,c){[].forEach.call(a,function(a){var b=a.cloneNode(!0);a.parentNode.replaceChild(b,a);b.addEventListener("click",d(a,c))})}function n(a){var c={products:[]};[].forEach.call(a,function(a){var d=b(a);a=(a=a.querySelector("button"))?a.getAttribute("data-mp3"):void 0;if(d&&a){var e=
{};e.asin=d;e.sample_url=a;c.products.push(e)}});return JSON.stringify(c)}var k={PAUSED:"pause",PLAYING:"play",BUFFERING:"load",ERROR:"reset",UNAVAILABLE:"reset"};(function(){a:{var a=["MobileJavaScriptBridge","AndroidJavaScriptBridge"];for(var b=0;b<a.length;++b){var d=a[b];if(f[d]){a=f[d];break a}}a=null}a&&"function"===typeof a.onPlaySampleClicked&&"function"===typeof a.onPlaySampleReady&&(b=document.querySelectorAll(".bc-trigger-playerbutton"),c(b,a),a.onPlaySampleStateChanged=e(),a.onPlaySampleReady(n(b)))})()});
g.when("AudiblejQuery","expanders","processing","button","image","ready").execute(function(a,e,b,d,c){function n(){a(".showMoreEpisodesButton").click(function(){var k=this;if(!k.classList.contains("bc-button-disabled")){d.disable(k);var f=b(k);f.activate();var g=a("#parentAsin").val(),h=a("#episodeSort").val(),m=a("#nextEpisodesPageNumber").val(),p=a("#episodesPageSize").val();a.ajax({url:"/pd/episodes",data:{asin:g,sort:h,page:m,pageSize:p}}).done(function(b){a("#showMore").replaceWith(b);e.init(document.querySelector(".episodeListPage"+
m));n();c.lazyLoad()}).always(function(){f.deactivate();d.enable(k)})}})}n();(function(){a("#episodeSort").change(function(){var b=a("#parentAsin").val(),d=a("#episodeSort").val(),f=a("#episodesPageSize").val();a.ajax({url:"/pd/episodes",data:{asin:b,sort:d,page:0,pageSize:f}}).done(function(b){var d=a(".episodeList");d.empty();d.append(b);e.init(document.querySelector(".episodeList"));n();c.lazyLoad()})})})()});g.when("ready").execute(function(){var a=document.querySelector(".adbl-extended-catalog-link");
a&&"undefined"!==typeof _satellite&&_satellite&&a.addEventListener("click",function(){_satellite.track("learnMoreAboutExtendedCatalogClick")})});g.when("ready").register("stickyTooltipInit",function(){function a(a){return a?function(){a.classList.add("bc-hidden")}:null}function e(b){if(b){b.firstElementChild.setAttribute("aria-describedby",b.id);b.parentElement.classList.contains("sticky-tooltip-parent")||(b.style.transform="translateX("+(b.nextElementSibling.offsetWidth-b.offsetWidth)/2+"px)");var d=
document.querySelector("#sticky-tooltip-close-"+b.id);d&&(d.addEventListener("click",a(b)),d.addEventListener("keypress",function(a){"Enter"===a.key&&b&&b.classList.add("bc-hidden")}),b.classList.remove("bc-hidden"));b.addEventListener("keydown",function(a){"Escape"===a.key&&b&&b.classList.add("bc-hidden")})}}document.querySelectorAll(".sticky-tooltip").forEach(function(a){e(a)})});g.when("AudiblejQuery","expanders","ready").execute(function(a){a=a(".contributor-info-expander .bc-expander-show-when-collapsed");
null!==a&&typeof a!==h&&0<a.length&&a.click(function(){"undefined"!==typeof _satellite&&_satellite&&_satellite.track("audible.mobilePdp.readMoreClicked")})});g.when("accessibleClick","focus","ready").execute(function(a,e){function b(b){if(b.detail){var c=document.getElementById("webDesktopView"),d=document.getElementById(b.detail+"-dialog"),f=document.getElementById(b.detail+"-modal-input"),g=b.detail+"-action-sheet",l=document.getElementById(g+"-input");d?d.setAttribute("open",!0):c&&"true"===c.value&&
f?f.click():l&&(l.click(),a.live("#"+g+" .bc-core-actionsheet-cancel",e.change({focusElement:b.target})))}}document.querySelectorAll(".product-metadata").forEach(function(a){a.addEventListener("clickOverflow",b)})});g.when("refMarkers","ready").execute(function(a){function e(c){if(c.detail&&b[c.detail]){var e=b[c.detail][f.location.host.split(".").pop()];c=a.build(d[c.detail],this);e&&(f.location.href=[e,c].join("?ref\x3d"))}}var b={dolby:{com:"https://"+f.location.host+"/ep/dolby-atmos",ca:"https://"+
f.location.host+"/ep/dolby-atmos",uk:"https://"+f.location.host+"/ep/dolby-atmos",de:"https://hilfe.audible.de/s/article/listen-in-dolby-atmos",fr:"https://aide.audible.fr/s/article/listen-in-dolby-atmos",au:"https://"+f.location.host+"/ep/dolby-atmos",jp:"https://help.audible.co.jp/s/article/audibleでdolby-atmos-ドルビーアトモス-の空間オーディオを利用して聴くには",it:"https://aiuto.audible.it/s/article/come-posso-ascoltare-titoli-in-audio-spaziale-con-dolby-atmos-su-audible","in":"https://help.audible.in/s/article/how-can-i-listen-to-spatial-audio-with-dolby-atmos-on-audible",
es:"https://ayuda.audible.es/s/article/qu%C3%A9-dispositivos-son-compatibles-con-la-reproducci%C3%B3n-dolby-atmos",br:""},whispersync:{com:"https://"+f.location.host+"/ep/wfs",ca:"https://help.audible.ca/s/article/what-is-whispersync-for-voice",uk:"https://"+f.location.host+"/ep/wfs",de:"https://hilfe.audible.de/s/article/listen-with-whispersync-for-voice",fr:"",au:"https://help.audible.com.au/s/article/listen-with-whispersync-for-voice",jp:"",it:"","in":"",es:"",br:""}},d={dolby:"dolby",whispersync:"wsfv"};
document.querySelectorAll(".product-metadata").forEach(function(a){a.addEventListener("clickListeningEnhancement",e)})});g.when("cloudPlayerLauncher","satelliteTrackingUtil","ready").execute(function(a,e){function b(b){var c=b.currentTarget.dataset.asin,d=b.currentTarget.dataset.isSample,f=b.currentTarget.dataset.amazonasin;b=b.currentTarget.dataset.marketplaceid;c&&(e.updateDigitalData(function(a){a.currentSampleAsin=c}),e.track("samplePlayerPlay"),f?a.openCloudPlayer(c,"a_pd_jpp_cloudplayer_"+c,
{isSample:d,amazonAsin:f,marketplaceId:b,isAmazonLaunch:!0}):a.openCloudPlayer(c,"a_pd_jpp_cloudplayer_"+c,{isSample:d}))}document.querySelectorAll('[id^\x3d"jpp-sample-button"]').forEach(function(a){a.addEventListener("click",b)})});g.when("ready").execute(function(){function a(a){a=document.querySelector("input[name\x3dpromoRadioButton]:checked");var b=document.getElementById("adbl_promo_direct_offer_heading"),c=document.getElementById("adbl_promo_free_trial_heading");a&&"promoRadioButton-1"===
a.value?(b.classList.remove("bc-hidden"),c.classList.add("bc-hidden")):(b.classList.add("bc-hidden"),c.classList.remove("bc-hidden"))}var e=document.getElementById("promoTopper");e&&e.addEventListener("click",a)});g.when("audibleMontanaJSBridge","clickstream","auiConsoleDebug","ready").execute(function(a,e,b){function d(){return function(c,d){d===a.PlaybackState.PLAYING&&(document.body.dispatchEvent(new Event("adblPlaying")),b("samplePlayMetrics.js Paused Sample Play."))}}a&&a.getCurrentSurface()||
b("samplePlayMetrics.js did not detect a surface compatible with Montana JSBridge. Skipping Execution.");a.registerOnPlaybackStateChangeHandler?a.registerOnPlaybackStateChangeHandler(d()):b("samplePlayMetrics.js Unable to register playbackStateChangeHandler with JSBridge.");a.onPlaySample&&document.addEventListener("adblPlaying",function(b){a.onPlaySample(b.target.dataset.asin,b);e.buildAndPost("Browse",null,b.target.dataset.asin,"PlaySample","pageTouch","N","Sample",b.target)});a.onPauseSample&&
document.addEventListener("adblPause",function(b){a.onPauseSample(b.target.dataset.asin,b);e.buildAndPost("Browse",null,b.target.dataset.asin,"PauseSample","pageTouch","N","Sample",b.target)});document.addEventListener("adblEnded",function(a){e.buildAndPost("Browse",null,a.target.dataset.asin,"FinishSample","pageTouch","N","Sample",a.target)})});g.when("satelliteTrackingUtil","ready").execute(function(a){var e=document.getElementById("social-proof-badge");e&&e.innerText!==h&&null!==e.innerText&&(a.updateDigitalData(function(a){a.social_proof_badge=
e.innerText}),a.track("changeSocialProofBadge"))});g.when("ready").execute(function(){function a(){return h&&"true"===h.getAttribute("aria-expanded")}function e(){r?g.show=!1:m?g.show=!0:p&&(g.show=!1)}function b(a){a=a[0];var b=a.boundingClientRect.top<l;m||(m=b&&.5>a.intersectionRatio);e()}function d(){if(c){var a=c.getBoundingClientRect().height;a!==t&&(l=t=a,q.disconnect(),q=new IntersectionObserver(b,{rootMargin:"-"+l+"px 0px 0px 0px",threshold:[0,.25,.5]}),q.observe(k))}}var c=document.querySelector("#nav-bar"),
g=document.querySelector("adbl-subnav"),k=document.getElementById("adbl-buy-box-container"),h=document.getElementById("navigation-top-search-button");if(g&&k){var l=0;c&&(l=c.getBoundingClientRect().height);var r=a(),m=!1,p=!1;f.addEventListener("scroll",function(){(p=0===f.scrollY)&&(m=!1);e()});var q=new IntersectionObserver(b,{rootMargin:"-"+l+"px 0px 0px 0px",threshold:[0,.25,.5]});q.observe(k);var t=l;c&&(f.addEventListener("resize",d),(new MutationObserver(d)).observe(c,{childList:!0,subtree:!0,
attributes:!0}));h&&(new MutationObserver(function(){r=a();e()})).observe(h,{attributes:!0,attributeFilter:["aria-expanded"]})}})});