name: Bug Report
description: Create a report to help us improve
title: "[Bug] <title>"
labels: [bug, needs triage]
assignees: []
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what do you see!
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to Reproduce
      description: |
        Steps to reproduce the behavior
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

        If applicable, please include information about any settings that may be relevant to this issue (e.g. selected theme, auto clear option, etc).

        Tip: You can attach screenshots by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Tell us what did you expect to happen!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Give us information about the app and your device
        - DDG App Version: (e.g. 5.25.0) Version can be found inside Settings -> Version
        - Device: [e.g. Pixel 2, Samsung s10]
        - OS: [e.g. Android 10]
      value: |
        - DDG App Version:
        - Device:
        - OS:
      render: markdown
    validations:
      required: false
