name: 'Assign Android Release Task in Asana'
description: 'Assigns the latest Asana Release task to the user who runs the workflow'
inputs:
  task_name:
    description: 'The name of the task to search for'
    required: true
  asana_token:
    description: 'Asana Personal Access Token'
    required: true
  project_gid:
    description: 'Asana Project GID to search within'
    required: true
  username:
    description: 'The Github username to search for'
    required: true
  github_token:
    description: 'GitHub token for private mapping repo access'
    required: true

outputs:
  task_id:
    description: 'The Asana task ID that was found and assigned'
    value: ${{ steps.find-asana-release-task.outputs.task_id }}

runs:
  using: 'composite'
  steps:
    - name: Find Asana User ID
      id: find-asana-user-id
      uses: duckduckgo/native-github-asana-sync@v2.3
      with:
        action: 'get-asana-user-id'
        github-username: ${{ github.actor }}
        github-pat: ${{ inputs.github_token }}

    - name: Find Asana Release task, assign it, and write ID to file
      id: find-asana-release-task
      shell: bash
      env: # Make inputs available as environment variables for easier access in the script
        INPUT_TASK_NAME: ${{ inputs.task_name }}
        INPUT_ASANA_TOKEN: ${{ inputs.asana_token }}
        INPUT_PROJECT_GID: ${{ inputs.project_gid }}
        INPUT_ASANA_USER_ID: ${{ steps.find-asana-user-id.outputs.asanaUserId }}
      run: |
        set -e # Exit immediately if a command exits with a non-zero status.
        echo "Searching for task: '$INPUT_TASK_NAME' in project GID: '$INPUT_PROJECT_GID'"
        
        asana_api_response=$(curl -s -X GET "https://app.asana.com/api/1.0/projects/${INPUT_PROJECT_GID}/tasks" \
          -H "Authorization: Bearer ${INPUT_ASANA_TOKEN}")
        
        # Using jq to extract the task_id - ensure it's robust
        # This will get the first matching task ID if multiple tasks have the same name.
        # Add error handling if multiple tasks with the same name is an issue.
        found_task_id=$(echo "$asana_api_response" | jq -r --arg TASK_NAME "$INPUT_TASK_NAME" '.data[] | select(.name == $TASK_NAME) | .gid | select(.)' | head -n 1)

        if [ -z "$found_task_id" ]; then
          echo "::error::No task with the exact name '$INPUT_TASK_NAME' found in project GID '$INPUT_PROJECT_GID'."
          exit 1
        else
          echo "Found Task ID: '$found_task_id'"
        fi

        echo "Assigning task ID $found_task_id to user ID $INPUT_ASANA_USER_ID"

        # Assign the task to the user
        response=$(curl -s -X PUT "https://app.asana.com/api/1.0/tasks/${found_task_id}" \
          -H "Authorization: Bearer ${INPUT_ASANA_TOKEN}" \
          -H "Content-Type: application/json" \
          -d "{\"data\": {\"assignee\": \"${INPUT_ASANA_USER_ID}\"}}")

        # Check if the assignment was successful
        status=$(echo $response | jq -r '.errors')

        if [ "$status" == "null" ]; then
          echo "Task $found_task_id successfully assigned to user INPUT_ASANA_USER_ID."
          echo "task_id=$found_task_id" >> "$GITHUB_OUTPUT"
        else
          echo "Failed to assign task: $status"
          exit 1
        fi

