name: 'Assign Android Release Task in Asana'
description: 'Assigns the latest Asana Release task to the user who runs the workflow'
inputs:
  ASANA_TASK_NAME:
    description: 'The name of the Asana task to search for'
    required: true
  ASANA_ACCESS_TOKEN:
    description: 'Asana Personal Access Token'
    required: true
  ASANA_PROJECT_ID:
    description: 'Asana Project ID to search the task in'
    required: true
  GITHUB_USERNAME:
    description: 'The Github username to search for'
    required: true

outputs:
  ASANA_TASK_URL :
    description: 'URL of the found Asana task'
    value: ${{ steps.check_for_changes.outputs.has_changes }}

runs:
  using: 'composite'
  steps:
    - name: Setup Java SDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.5
        cache-read-only: false
        cache-overwrite-existing: true
        gradle-home-cache-cleanup: true

    - name: Find task in Asana and assign it to the correct user
      shell: bash
      run: |
        cd ${{ github.action_path }}
        ./gradlew run --build-cache
      env:
        ASANA_ACCESS_TOKEN: ${{ inputs.ASANA_ACCESS_TOKEN }}
        ASANA_PROJECT_ID: ${{ inputs.ASANA_PROJECT_ID }}
        ASANA_TASK_NAME: ${{ inputs.ASANA_TASK_NAME }}
        GITHUB_USERNAME: ${{ inputs.GITHUB_USERNAME }}