# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Release"
  lane :deploy_github do

    props = property_file_read(file: "app/version/version.properties")
    version = props["VERSION"]
    releaseNotes = File.read("../app/version/release-notes")
    apkPath = ENV["APK_PATH"]
    token = ENV["GITHUB_UPLOAD_TOKEN"]

    UI.message ("Releasing new app version\nVersion: #{version}\nRelease Notes:\n=====\n#{releaseNotes}\n=====\n")
    UI.message ("APK Path: #{apkPath}")

    UI.header ("Uploading #{version} APK to GitHub")

    end
end