name: Maestro Flow Analyzer
description: Parse Maestro Cloud flow results JSON and emit a summary status

inputs:
  flow_results_json:
    description: Raw MAESTRO_CLOUD_FLOW_RESULTS JSON array
    required: true
  console_url:
    description: Maestro console URL (optional, for logging)
    required: false
    default: ''
  upload_status:
    description: Maestro upload status (optional, for logging)
    required: false
    default: ''
  app_binary_id:
    description: Maestro app binary ID (optional, for logging)
    required: false
    default: ''
  treat_canceled_as_failure:
    description: Treat CANCELED flows as failures (true/false)
    required: false
    default: 'false'

outputs:
  flow_summary_status:
    description: Derived status (success, failure, canceled_present, empty_results, unknown_format)
    value: ${{ steps.analyze.outputs.flow_summary_status }}

runs:
  using: composite
  steps:
    - name: Analyze Maestro flow results
      id: analyze
      shell: bash
      env:
        FLOW_RESULTS_JSON: ${{ inputs.flow_results_json }}
        CONSOLE_URL: ${{ inputs.console_url }}
        UPLOAD_STATUS: ${{ inputs.upload_status }}
        APP_BINARY_ID: ${{ inputs.app_binary_id }}
        TREAT_CANCELED_AS_FAILURE: ${{ inputs.treat_canceled_as_failure }}
      run: |
        set -eo pipefail

        echo "Console URL: ${CONSOLE_URL}"
        echo "Upload Status: ${UPLOAD_STATUS}"
        echo "App Binary ID: ${APP_BINARY_ID}"

        flow_results_json="${FLOW_RESULTS_JSON}"
        echo "Raw Flow Results JSON: ${flow_results_json}"
        final_status="success"

        if ! echo "$flow_results_json" | jq -e . > /dev/null 2>&1; then
          echo "::warning::MAESTRO_CLOUD_FLOW_RESULTS is not valid JSON or is empty."
          final_status="unknown_format"
        else
          if echo "$flow_results_json" | jq -e '. | length > 0' > /dev/null; then
            :
          else
            echo "::warning::MAESTRO_CLOUD_FLOW_RESULTS is an empty array. No flows reported."
            final_status="empty_results"
          fi

          if echo "$flow_results_json" | jq -e '.[] | select(.status=="ERROR")' > /dev/null; then
            echo "::error::At least one Maestro flow has status: ERROR."
            final_status="failure"
          fi

          if echo "$flow_results_json" | jq -e '.[] | select(.status=="CANCELED")' > /dev/null; then
            echo "::warning::At least one Maestro flow has status: CANCELED."
            if echo "$TREAT_CANCELED_AS_FAILURE" | grep -qi '^true$'; then
              final_status="failure"
            elif [ "$final_status" != "failure" ]; then
              final_status="canceled_present"
            fi
          fi
        fi

        echo "Final determined status: $final_status"
        echo "flow_summary_status=$final_status" >> "$GITHUB_OUTPUT"
