/*
 * Copyright (c) 2026 DuckDuckGo
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.duckduckgo.app.tabs.ui

import com.duckduckgo.browser.api.ui.BrowserScreens.TabSwitcherScreenWithParams
import com.duckduckgo.browsermode.api.BrowserMode
import com.duckduckgo.navigation.api.GlobalActivityStarter.DeeplinkActivityParams
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

/**
 * Verifies that the Tab Switcher is reachable via an RMF `navigation` action, carrying the target
 * [BrowserMode] as a JSON payload. This is what lets the Fire Tabs promo open the Tab Switcher in Fire
 * mode without a bespoke action type — the [com.duckduckgo.remote.messaging.impl.mappers.NavigationActionMapper]
 * resolves the deeplink through [GlobalActivityStarter], which delegates to the mapper generated here.
 *
 * The mapper under test is generated by [com.duckduckgo.anvil.ksp.ContributeToActivityStarterProcessor]
 * from the `@ContributeToActivityStarter(TabSwitcherScreenWithParams::class, screenName = ...)` annotation on
 * [TabSwitcherActivity].
 */
class TabSwitcherScreenDeeplinkMapperTest {

    private val mapper = TabSwitcherActivity_TabSwitcherScreenWithParams_Mapper()

    @Test
    fun whenNavigationDeeplinkCarriesFireModeThenMapsToTabSwitcherScreenWithParamsInFireMode() {
        val result = mapper.map(
            DeeplinkActivityParams(
                screenName = "tabSwitcherWithParams",
                jsonArguments = """{"browserMode":"FIRE"}""",
            ),
        )

        assertEquals(TabSwitcherScreenWithParams(BrowserMode.FIRE), result)
    }

    @Test
    fun whenNavigationDeeplinkCarriesRegularModeThenMapsToTabSwitcherScreenWithParamsInRegularMode() {
        val result = mapper.map(
            DeeplinkActivityParams(
                screenName = "tabSwitcherWithParams",
                jsonArguments = """{"browserMode":"REGULAR"}""",
            ),
        )

        assertEquals(TabSwitcherScreenWithParams(BrowserMode.REGULAR), result)
    }

    @Test
    fun whenDeeplinkScreenNameDoesNotMatchThenReturnsNull() {
        val result = mapper.map(
            DeeplinkActivityParams(
                screenName = "someOtherScreen",
                jsonArguments = """{"browserMode":"FIRE"}""",
            ),
        )

        assertNull(result)
    }
}
