name: Create Android Release Task

on:
  push:
    branches: ["develop"]

  workflow_dispatch:
    inputs:
      app-version:
        description: 'App Version for Release'
        required: true
        default: '1.0.0'

env:
  ASANA_PAT: ${{ secrets.GH_ASANA_SECRET }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create_release_task:
    name: Create Release task in Asana
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Release Bridge from Homebrew
        run: |
          brew tap cdrussell/aarb
          brew install aarb

      - name: Create task in Asana
        run: |          
          AndroidAsanaBridge version=${{ github.event.inputs.app-version }} action=createRelease,tagPendingTasks,addLinksToDescription board=fake

      - name: Get Asana User Id
        id: get-asana-user-id
        shell: bash
        run: |
          user_id="$(yq ."${{ github.actor }}" ./.github/github_asan a_mapping.yml)"
          if [[ -z "$user_id" || "$user_id" == "null" ]]; then
            echo "::warning::Asana User ID not found for GitHub handle: ${{ inputs.github-handle }}"
          else
            echo "{user-id}=${user_id}" >> $GITHUB_OUTPUT        
          fi

  create-tag:
    name: Create and Push git tag for version
    needs: create_release_task
    runs-on: ubuntu-20.04

    steps:
      - name: Prepare fastlane
        run: bundle install

      - name: Use fastlane lane to create and push tag
        id: make_release_branch
        run: |
          bundle exec fastlane release
