name: Mark task as complete on merge

on:
  pull_request:
    types: [closed]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: aitorvs/github-asana-action@0.1.0
        if: github.event.pull_request.merged
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          trigger-phrase: "Task/Issue URL:"
          action: 'complete-task'
          is-complete: true
