name: Add a comment

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: aitorvs/github-asana-action@0.2.1
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          trigger-phrase: "Task/Issue URL:"
          action: 'add-comment'
          is-pinned: true
