name: Add a comment

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: set pr number
        run: echo "::set-env name=PR_NUMBER::$(echo -n "${GITHUB_REF}" | awk 'BEGIN { FS = "/" } ; { print $3 }')"
      - uses: insurify/github-asana-action@v1.0.3
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          task-comment: 'View Pull Request Here: '
          trigger-phrase: 'Task/Issue URL:'
