name: Add a comment

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: aitorvs/github-asana-action@0.1.2
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          task-comment: 'PR: '
          trigger-phrase: "Task/Issue URL:"