name: Instrumentation tests

on:
  push:
    branches:
      - feature/marcos/add_maestro_to_ci
  schedule:
    - cron: '0 4 * * *' # run at 3 AM UTC
  workflow_dispatch:

jobs:
  instrumentation_tests:
    runs-on: macos-latest
    name: Instrumentation tests

    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Install maestro
        run: |
          brew tap mobile-dev-inc/tap
          brew install maestro

      - name: Android checks
        uses: reactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          ndk: 21.0.6113669
          arch: x86_64
          profile: Nexus 5
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: cd .mobiledev && maestro test test.yaml || adb shell /system/bin/screencap -p /data/local/tmp/screenshot.png && adb pull /data/local/tmp/screenshot.png screenshot.png;

      - name: Upload screenshot
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: device-screenshot
          path: screenshot.png