name: Maestro tests

on:
  push:
    branches:
      - feature/marcos/add_maestro_to_ci
  schedule:
    - cron: '0 4 * * *' # run at 3 AM UTC
  workflow_dispatch:

jobs:
  instrumentation_tests:
    runs-on: macos-latest
    name: Instrumentation tests
    strategy:
      fail-fast: false
      matrix:
        api-level: [ 23, 29, 31 ]

    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install maestro
        run: |
          brew tap mobile-dev-inc/tap
          brew install maestro

      - name: Decode keys
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.FAKE_RELEASE_PROPERTIES }}
          fileName: ddg_android_build.properties
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Decode key file
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.FAKE_RELEASE_KEY }}
          fileName: android
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew assemblePlayRelease

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-maestro

      - name: Android checks
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          ndk: 21.0.6113669
          arch: x86_64
          profile: Nexus 5
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Android checks
        uses: reactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          ndk: 21.0.6113669
          arch: x86_64
          profile: Nexus 5
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
          disable-animations: true
          script:  |
            sleep 5; adb shell am broadcast -a android.intent.action.CLOSE_SYSTEM_DIALOGS;
            ./gradlew installPlayRelease || touch sorry_but_tests_are_failing
            sleep 5; 
            maestro --platform android test .mobiledev/test.yaml || touch sorry_but_tests_are_failing
            adb shell screencap -p /data/local/tmp/Screenshot.png; adb pull /data/local/tmp/Screenshot.png Screenshot.png;
            test ! -f sorry_but_tests_are_failing

      - name: Upload screenshot
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: device-screenshot-${{ matrix.api-level }}
          path: ./*Screenshot.png