name: Instrumentation tests

on:
  push:
    branches:
      - feature/marcos/add_maestro_to_ci
  schedule:
    - cron: '0 4 * * *' # run at 3 AM UTC
  workflow_dispatch:

jobs:
  instrumentation_tests:
    runs-on: macos-latest
    name: Instrumentation tests

    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Create folder
        if: always()
        run: mkdir apk

      - name: Install maestro
        run: |
          brew tap mobile-dev-inc/tap
          brew install maestro

      - name: Decode keys
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.FAKE_RELEASE_PROPERTIES }}
          fileName: ddg_android_build.properties
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Decode key file
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.FAKE_RELEASE_KEY }}
          fileName: android
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Android checks
        uses: reactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          ndk: 21.0.6113669
          arch: x86_64
          profile: Nexus 5
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew installPlayRelease && cd .mobiledev && maestro test test.yaml;

      - name: Bundle the Android CI checks report
        if: always()
        run: find . -type d -name 'reports' | zip -@ -r android-checks-report.zip

      - name: Upload the Android CI checks report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: android-checks-report
          path: android-checks-report.zip