name: NetP Nightly Release

on:
  push:
    branches:
      - feature/netp-develop
    paths-ignore:
      - '**.md'
      - '.github/**'

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build_debug_apk:
    name: Build release apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.3'

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleInternalRelease

      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/internal/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload the release apk to AppCenter
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: avianasanchez/ddg-netp
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Internal
          file: ${{steps.sign_app.outputs.signedReleaseFile}}
          notifyTesters: true
          debug: true
