name: Pull Request Review/Mentions -> Sync With Asana

on:
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  sync:
    name: Sync PR review/mentions with Asana
    runs-on: ubuntu-latest
    steps:
      - name: Checkout native actions repo
        uses: actions/checkout@v4
        with:
          ref: v2.6.0
          # Do not change the below path (the composite expects it)
          path: native-github-asana-sync
          repository: duckduckgo/native-github-asana-sync

      # Posts canned review-event notes, and forwards review summaries and
      # inline comments @-mentioning a user.
      - name: Sync PR review/mentions with Asana
        uses: ./native-github-asana-sync/.github/actions/pr-review-notifications
        with:
          trigger-phrase: "Task/Issue URL:"
          asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          user-map: ${{ vars.GH_ANDROID_USER_MAP }}
