name: Report Workflow Failed

on:
  workflow_dispatch:

env:
  MM_AUTH_TOKEN: ${{ secrets.MM_AUTH_TOKEN }}
  MM_TEAM_ID: ${{ secrets.MM_TEAM_ID }}
  APP_VERSION: "5.220.0"
  emoji_info: ":information_source:" # ℹ️

jobs:
  report-release-error:
    name: Notify Mattermost
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./.github/actions/scripts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GT_DAXMOBILE }}
          fetch-depth: 0
          ref: feature/david/11-14-gha_notify_mattermost

      - name: Make sure script can be executed
        run: |
          chmod +x send_chat_message.sh          

      - name: Send Release start message
        run: |
          echo -n '::notice title=Inputs::' && echo '${{ toJson(inputs) }}' | sed -z 's_\n_%0A_g'; echo
          message="Release ${{ env.APP_VERSION }} by @${{ github.actor }} has started."
          message+="See https://github.com/duckduckgo/Android/actions/runs/${{ github.run_id }}"
          ./send_chat_message.sh '${{env.emoji_info}}'" ${message}"