name: Report Workflow Failed

on:
  workflow_dispatch:

env:
  APP_VERSION: "5.220.0"
  emoji_start: ":flight_departure:" # 🛫 or ':soon:' 🔜
  emoji_info: ":information_source:" # ℹ️

jobs:
  report-release-error:
    name: Notify Mattermost
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./.github/actions/scripts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GT_DAXMOBILE }}
          fetch-depth: 0

      - name: Send test message
        id: send-test-message
        uses: duckduckgo/native-github-asana-sync@v1.5
        with:
          mattermost-token: ${{ secrets.MM_AUTH_TOKEN }}
          mattermost-team-id: ${{ secrets.MM_TEAM_ID }}
          mattermost-channel-name: 'david-mattermost-test'
          mattermost-message: ":flight_departure:" Android Release ${{ env.APP_VERSION }} started by @${{ github.actor }}. https://github.com/duckduckgo/Android/actions/runs/${{ github.run_id }}
          action: 'send-mattermost-message'