name: Release - Upload Bundle to Play Store

on:
  workflow_dispatch:

env:
  ASANA_PAT: ${{ secrets.GH_ASANA_SECRET }}

jobs:
  create-tag:
    name: Generate and upload nightly bundle to Play Store Internal track
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fetch Latest Git Tag
        id: fetch_tag
        run: |          
          git fetch --tags
          TAG=$(git describe --tags --abbrev=0)
          echo "latest_tag=$TAG" >> $GITHUB_ENV        

      - name: Show the latest tag
        run: |
          echo "The latest git tag is: ${{ steps.fetch_tag.outputs.latest_tag }}"

      - name: Generate nightly version name
        id: generate_version_name
        run: |
          output=$(./gradlew getBuildVersionName -PversionNameSuffix=-nightly -PlatestTag= ${{ steps.fetch_tag.outputs.latest_tag }} -q | tail -n 1)                  
          echo "version=$output" >> $GITHUB_OUTPUT

      - name: Use the captured output
        run: |
          echo "The captured output is: ${{ steps.generate_version_name.outputs.version }}"

      - name: Use the captured bundle path
        run: |
          echo "The generated app bundle is located at: ${{ steps.capture_output.outputs.bundle_path }}"