name: Release - Upload Bundle to Play Store

on:
  workflow_dispatch:

env:
  ASANA_PAT: ${{ secrets.GH_ASANA_SECRET }}

jobs:
  create-tag:
    name: Generate and upload nightly bundle to Play Store Internal track
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 20

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate nightly version name
        id: generate_version_name
        run: |
          output=$(./gradlew -q getBuildVersionName -PversionNameSuffix=-nightly -q | tail -n 1)                  
          echo "version=$output" >> $GITHUB_OUTPUT

      - name: Use the captured output
        run: |
          echo "The captured output is: ${{ steps.generate_version_name.outputs.version }}"

      - name: Use the captured bundle path
        run: |
          echo "The generated app bundle is located at: ${{ steps.capture_output.outputs.bundle_path }}"