name: Report Workflow Failed

on:
  workflow_dispatch:

env:
  MM_AUTH_TOKEN: ${{ secrets.MM_AUTH_TOKEN }}
  MM_TEAM_ID: ${{ secrets.MM_TEAM_ID }}

jobs:
  report-release-error:
    name: Notify Mattermost
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GT_DAXMOBILE }}
          fetch-depth: 0
          ref: feature/david/11-14-gha_notify_mattermost

      - name: Run a script
        run: |
          chmod +x send_chat_message.sh
          ./send_chat_message.sh "This is a test"