name: Release - Upload Bundle to Play Store

on:
  workflow_dispatch:

env:
  ASANA_PAT: ${{ secrets.GH_ASANA_SECRET }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-tag:
    name: Generate and upload nightly bundle to Play Store Internal track
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Decode upload keys
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.UPLOAD_RELEASE_PROPERTIES }}
          fileName: ddg_android_build_upload.properties
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Decode key file
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.UPLOAD_RELEASE_KEY }}
          fileName: android
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Assemble the bundle
        run: ./gradlew bundleInternalRelease -PversionNameSuffix=-nightly -PuseUploadSigning

      - name: Capture App Bundle Path
        id: capture_output
        run: |          
          output=$(ls app/build/outputs/bundle/internalRelease/*.aab)
          echo "bundle_path=$output" >> $GITHUB_OUTPUT

      - name: Use the captured bundle path
        run: |
          echo "The generated app bundle is located at: ${{ steps.capture_output.outputs.bundle_path }}"