name: Generate Android Release Bundle

on:
  push:
    branches: ["develop"]

  workflow_dispatch:
    inputs:
      app-version:
        description: 'App Version for Release'
        required: true
        default: '1.0.0'

env:
  ASANA_PAT: ${{ secrets.GH_ASANA_SECRET }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-universal-bundle:
    name: Builds release flavour of the app and pushes it to Play Store for Signing
    needs: create-tag
    runs-on: ubuntu-20.04

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
         java-version: '17'
         distribution: 'adopt'

      - name: Create folder
        run: mkdir apk

      - name: Decode keys
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.FAKE_RELEASE_PROPERTIES }}
          fileName: ddg_android_build.properties
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Decode key file
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.FAKE_RELEASE_KEY }}
          fileName: android
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Assemble release APK
        run: ./gradlew assemblePlayRelease -Pforce-default-variant

      - name: Move APK to new folder
        run: find . -name "*.apk"  -exec mv '{}' apk/release.apk \;

      - name: Create Asana task when workflow failed
        if: ${{ failure() }}
        id: create-failure-task
        uses: duckduckgo/native-github-asana-sync@v1.1
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          asana-project: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana-section: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          asana-task-name: GH Workflow Failure - Generate Android Release Bundle
          asana-task-description: Generate Android Release Bundle has failed. See https://github.com/duckduckgo/Android/actions/runs/${{ github.run_id }}
          action: 'create-asana-task'