name: Report Workflow Failed

on:
  workflow_dispatch:

env:
  ASANA_PAT: ${{ secrets.GH_ASANA_SECRET }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  report-release-error:
    name: Create Asana Task
    runs-on: ubuntu-20.04

    steps:
      - name: Create Asana task when workflow failed
        uses: honeycombio/gha-create-asana-task@main
        with:
          asana-secret: ${{ secrets.GH_ASANA_SECRET }}
          asana-workspace-id: ${{ secrets.GH_ASANA_WORKSPACE_ID }}
          asana-project-id: ${{ secrets.GH_ASANA_AOR_PROJECT_ID }}
          asana-section-id: ${{ secrets.GH_ASANA_INCOMING_ID }}
          asana-task-name: GH Workflow Failure - Production Release
          asana-task-description: The end to end workflow has failed. See https://github.com/duckduckgo/Android/actions/runs/${{ github.run_id }}